# Site settings
title: wandrr
email: rlynjb at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a blog about tech and maybe random stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rlynjb.github.io/wandrr" # the base hostname & protocol for your site
twitter_username: rlynjb08
github_username:  rlynjb

# Build settings
markdown: kramdown

# Permalink settings
permalink: /:title
